version: '3.8'

services:
  api-gateway:
    build:
      context: ../api-gateway   
      dockerfile: Dockerfile
      secrets:
        - GITHUB_TOKEN
    ports:
      - "${PORT_API}:${PORT_API}"
    environment:
      - APP_PORT=${PORT_API}
      - AUTH_SERV_ADDR=auth-service
      - AUTH_SERV_PORT=${PORT_AUTH}
      - COURSE_SERV_ADDR=course-service
      - COURSE_SERV_PORT=${PORT_COURSE}
      - INVENTORY_SERV_ADDR=inventory-service
      - INVENTORY_SERV_PORT=${PORT_INVENTORY}
    depends_on:
      - auth-service

  migrate:
    image: migrate/migrate
    profiles: ["manual"]

  auth-db:
    image: postgres:15-alpine
    container_name: loanem-auth-db
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
      secrets:
        - GITHUB_TOKEN
    environment:
      - APP_PORT=${PORT_AUTH}
      - DB_HOST=${AUTH_DB_HOST}
      - DB_PORT=${AUTH_DB_PORT}
      - DB_USER=${AUTH_DB_USER}
      - DB_PASS=${AUTH_DB_PASS}
      - DB_NAME=${AUTH_DB_NAME}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_EXPIRE=${JWT_EXPIRE}
    volumes:
      - ./secrets/auth:/run/secrets/auth:ro
    depends_on:
      - auth-db

  course-db:
    image: postgres:15-alpine
    container_name: loanem-course-db
    environment:
      POSTGRES_USER: ${COURSE_DB_USER}
      POSTGRES_PASSWORD: ${COURSE_DB_PASS}
      POSTGRES_DB: ${COURSE_DB_NAME}
    volumes:
      - course_db_data:/var/lib/postgresql/data

  course-service:
    build:
      context: ../course-service
      dockerfile: Dockerfile
      secrets:
        - GITHUB_TOKEN
    environment:
      - APP_PORT=${PORT_COURSE}
      - DB_HOST=${COURSE_DB_HOST}
      - DB_PORT=${COURSE_DB_PORT}
      - DB_USER=${COURSE_DB_USER}
      - DB_PASS=${COURSE_DB_PASS}
      - DB_NAME=${COURSE_DB_NAME}
    depends_on:
      - course-db

  inventory-db:
    image: postgres:15-alpine
    container_name: loanem-inventory-db
    environment:
      POSTGRES_USER: ${INVENTORY_DB_USER}
      POSTGRES_PASSWORD: ${INVENTORY_DB_PASS}
      POSTGRES_DB: ${INVENTORY_DB_NAME}
    volumes:
      - inventory_db_data:/var/lib/postgresql/data

  inventory-service:
    build:
      context: ../inventory-service
      dockerfile: Dockerfile
      secrets:
        - GITHUB_TOKEN
    environment:
      - APP_PORT=${PORT_INVENTORY}
      - DB_HOST=${INVENTORY_DB_HOST}
      - DB_PORT=${INVENTORY_DB_PORT}
      - DB_USER=${INVENTORY_DB_USER}
      - DB_PASS=${INVENTORY_DB_PASS}
      - DB_NAME=${INVENTORY_DB_NAME}
    depends_on:
      - inventory-db

volumes:
  auth_db_data:
  course_db_data:
  inventory_db_data:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
    